sudo: false
language: java
dist: trusty
jdk:
  - oraclejdk8
  
script: "./travis.sh"
cache:
  directories:
    - .cache
before_script:
 - sudo apt-get -qq update
 - sudo apt-get install ant-optional
 - chmod +x travis.sh

env:
  - PHPSTORM_ENV=2017.3.2
  - PHPSTORM_ENV=eap
  - IDEA_ENV=2017.3.7

matrix:
  allow_failures:
    - env: PHPSTORM_ENV=eap
